### ISSUE TITLE
[Feature request] Double ended queue functionality

### ISSUE THREAD

**Issue by catan85** [i-e-b/DiskQueue#10]
Are you planning to implement a double ended queue functionality?
Otherwise some functionality that allow to dequeue the last element without removing it from the stack. 
I need to do some operations that could fail after the dequeuing, in this case I would like to put the element again in the list but it will be the first dequeued the in the next iteration.
Do you think it is possible to implement something like that?

**Comment by i-e-b** [comment]
Making the queue double ended would need a complete rewrite, so I don't plan to implement that.

However, the behaviour you describe is already supported: if you dispose of the queue object **without** calling `Flush`, the dequeue will be rolled back - if you flush after each successful item, and dispose on failure (e.g. by throwing an exception out of a using block), reopening the queue will result in the previous failed item being provided again. 
This is described in the read-me.
