### ISSUE TITLE
[Question] Should queue ever cleanup

### ISSUE THREAD

**Issue by ronnyek** [i-e-b/DiskQueue#11]
I've got examples of my own running... one thing writing to the queue, and another thing reading from the queue at a decent rate.

What I'm noticing is that even though i'm dequeue-ing with a flush, data.0 file in the queue folder continues to grow.... I'm assuming meta.state keeps track of where the "stating position" is in data.0, and thus stopping the app, and restarting doesn't just start replaying all those old queue items... but I've noticed data.0 seems to basically grow indefinitely, regardless if the queue'd items are getting dequeued very shortly after they are being queued.

Is there anything that will basically take whats left in data.0 to process and write that to a new file, and delete data.0?

**Comment by ronnyek** [comment]
Seems like after the data.0 file grew to > 32mb, it stopped growing, created a data.1 that's approximately the same size, deleted data.0, and is internally re-writing bytes in that file.

**Comment by ronnyek** [comment]
seems like it just carries forward a new data.x file... is there any risk of running long enough where the queue files get exhausted? Eg, overflows the int value? 

Is there some practice we should be following like on start of my app check to see if queue is empty, if so  delete the folder so we "reset" the data file handling?

**Comment by i-e-b** [comment]
Sorry for the slow reply.
Yes, the disk-queue log rotates. With 32mb files and a 32 bit counter, it will overflow after about 64 exabytes. If you're sending that much data, I'd recommend using a more serious queuing system.

Having said that, resetting or having a sliding window of files would be a neat feature; but I doubt I'll have time for it any time soon. Pull requests more than welcome :-)
