### ISSUE TITLE
Diskqueue.dll version still 1.0.0 ?

### ISSUE THREAD

**Issue by stephentissot** [i-e-b/DiskQueue#14]
Hello.

I am not 100% sure, but it looks like the file version in 1.3.1 nuget package is still 1.0.0. This cause an error with our Installshield installer when trying to upgrade our software.
Can this be fixed in a 1.3.2 package ?
Thanks. Stephen

**Comment by i-e-b** [comment]
Sure, I'll do this as soon as I can.

**Comment by i-e-b** [comment]
This should be available at https://www.nuget.org/packages/DiskQueue/1.3.2 when it's finished processing.
Please re-open this issue if this doesn't work.

**Comment by stephentissot** [comment]
Thanks a lot, it works
