### ISSUE TITLE
System.Security.AccessControl.PrivilegeNotHeldException

### ISSUE THREAD

**Issue by wwaldner-amtelco** [i-e-b/DiskQueue#25]
Running as a normal user, the library continuously outputs the the said exception.  When running as administrator, I do not see the exception.  Is there a way to eliminate these exceptions? These are caught inside the library and do not seem to cause harm, but seems like if the exceptions are thrown, something is not quite right.

**Comment by i-e-b** [comment]
Thanks for the report. I've not seen that one before.

Can you tell me what OS (& version), and what dotnet runtime you are using?

Also, do you see these only when running inside a debugger, or also when running as a stand-alone process?

**Comment by wwaldner-amtelco** [comment]
.net 4.72, Windows 11 Pro.  Seeing the errors in debugger.  Ultimately, I need to run this in the System account in a Windows Service.  I think running in the system account it would not happen, but I am not sure of that.  I was going to check, but don't know how to monitor exceptions at runtime outside debugger.

As an aside, I was hoping to update to latest version.  We have had some issues with 1.6.0 throwing exception in the Flush() function after dequeuing items.  There was a file in use exception that occurs and this corrupted the queue.  After this ex, we are no longer able to read from the queue.  We can write items, but can't read.  I seems like there have been some fixes relating to this in the new version so I was hopeful.  If I could get past this issue...

**Comment by i-e-b** [comment]
Can you please try version 1.6.6 ( https://www.nuget.org/packages/DiskQueue/1.6.6 )
and let me know if you still get flush exceptions -- and the message of exception if you do.

**Comment by wwaldner-amtelco** [comment]
Still get the exception

System.Security.AccessControl.PrivilegeNotHeldException
  HResult=0x80070005
  Message=The process does not possess the 'SeSecurityPrivilege' privilege which is required for this operation.
  Source=mscorlib
  StackTrace:
   at System.Security.AccessControl.Privilege.ToggleState(Boolean enable)

**Comment by i-e-b** [comment]
Thanks. I will try to investigate further.

**Comment by i-e-b** [comment]
I think this is being caused a feature added for sharing data between a Windows Service and an interactive app.
I've turned this off by default in version 1.6.7 ( https://www.nuget.org/packages/DiskQueue/1.6.7 )

It can be turned back on with `PersistentQueue.DefaultSettings.SetFilePermissions = true`

Please try version 1.6.7 and let me know if it works for you.

**Comment by wwaldner-amtelco** [comment]
Yes, that does seem to do the trick.

**Comment by i-e-b** [comment]
Thanks. Will close this now. Please feel free to re-open if you have further problems.
