### ISSUE TITLE
data.0 file does not decrease in size when doing a dequeue? 

### ISSUE THREAD

**Issue by JeremyGEA** [i-e-b/DiskQueue#27]
Version: 1.6.7

Expected Behavior:
When I dequeue something from the queue, I expect the data.0 file to decrease in size or the item to be removed.

Observed Behavior:
The data.0 file remains the same size even though the queue is considered empty.

Description:
I would expect as the queue data is removed/dequeued from the queue that the data.0 file would decrease in size as well but it only grows.

Dequeue Code:
`public void Dequeue()
{
            using var queue = PersistentQueue.WaitFor(_queueStorage, TimeSpan.FromSeconds(30));
            using var session = queue.OpenSession();
            data = session.Dequeue();
            if(data != null)
                session.Flush(); // remove old entry
}`

Enqueue Code:
`
public void Enqueue(string entry)
{
            using var queue = PersistentQueue.WaitFor(_queueStorage, TimeSpan.FromSeconds(30));
            using var session = queue.OpenSession();
            session.Enqueue(Encoding.Unicode.GetBytes(entry));
            session.Flush();
}
`

**Comment by i-e-b** [comment]
Hi, thanks for the comment.

DiskQueue uses a rolling append-only log. All files only grow in size, until the rolling size is reached, at which point old files will be deleted if they contain no active entries (assuming I remember correctly).

This is done to prevent problems with re-sizing files, and moving ranges of bytes.

If you are working in a size-constrained environment, you might want to reduce the maximum log size using this constructor:
```
public PersistentQueue(string storagePath, int maxSize, bool throwOnConflict = true)
```
Where `maxSize` is the rolling log file size limit in bytes.

**Comment by JeremyGEA** [comment]
Since I am using the WaitFor method to create the PersistantQueue, I do not have access to that constructor.

**Comment by i-e-b** [comment]
That I can fix 😊
https://www.nuget.org/packages/DiskQueue/1.6.8

See `WaitFor(string storagePath, int maxSize, bool throwOnConflict, TimeSpan maxWait)` or the `WaitFor<T>` equivalent.

`throwOnConflict` should be `true` to match previous behaviour.
