### ISSUE TITLE
Lock issue after power failure.

### ISSUE THREAD

**Issue by stefandascalu64** [i-e-b/DiskQueue#29]
Hello.

I'm running into a weird issue that seems to occur if there is a power failure. I'm going to describe the scenario and please tell me if there's something I'm missing and I'm using the queue wrong.

Scenario:
1. app starts with PID 1000 and uses the queue.
2. power failure occurs.
3. another process starts with PID 1000 and my app starts with some other PID
4. ```StandardFileDriver.IsRunning``` assumes that it's a valid lock even though the process in question has nothing to do with the file.

Since this is an issue that can occur with the app crashing I'm thinking that adding the process ```StartTime``` to the lock file could be a possible fix since it would allow to double check that PID refers to the same process (not only the same name) while also having a fixed byte length for the lock file.

**Comment by i-e-b** [comment]
Hi.
Thanks for the report. That is a good idea for a solution.

I can't give a time-frame for implementing this, but PRs always welcome

**Comment by stefandascalu64** [comment]
Hello again. Sorry for the late reply.

I'm trying to push a branch with the fix but I'm getting an access denied response. I'm guessing I need some permissions to perform the push.

`Pushing fix/lock-overlap-of-pid
Remote: Permission to i-e-b/DiskQueue.git denied to stefandascalu64.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/i-e-b/DiskQueue.git/': The requested URL returned error: 403`

**Comment by i-e-b** [comment]
You'll need to fork the repository, make the changes in your own fork, then open a pull request in GitHub.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by stefandascalu64** [comment]
Sorry about that. A bit new to this.
Created the PR and awaiting your feedback.
