### ISSUE TITLE
Console.WriteLine

### ISSUE THREAD

**Issue by orith94** [i-e-b/DiskQueue#31]
Thank you for the excellent package! 
I have a request: in several places in the code, you use Console.writeLine, which we can't override. Could this be addressed? Appreciate it!

Orit

**Comment by i-e-b** [comment]
Yes, this probably should be fixed. Will do now as it's lunchtime...

**Comment by i-e-b** [comment]
When https://www.nuget.org/packages/DiskQueue/1.7.1 becomes available, you should be able to assign `DiskQueue.PersistentQueue.Log` with any `Action<string>` to replace console output.
This can be `DiskQueue.PersistentQueue.Log = _ => { };` if you don't want any internal logs at all.

**Comment by jsyrjala** [comment]
I noticed that https://www.nuget.org/packages/DiskQueue/1.7.1 is now available but the related commits seem to be missing from GitHub.

**Comment by orith94** [comment]
Thank you so much for your quick response !
