### ISSUE TITLE
data.x files not getting cleaned up

### ISSUE THREAD

**Issue by wwaldner-amtelco** [i-e-b/DiskQueue#34]
I have an issue where the data files seem to keep accumulating, even though all items have been dequeued.

My observation is that each time the queue backs up and acccumlates a number of data files, it never gets around to actually deleting all the data.x files even though all the items eventually get dequeued.

Do you have any ideas what I could look at to see why this happens?

**Comment by wwaldner-amtelco** [comment]
I does seem to 'eventually' come around and clean up the files. Is this on a timer or something? It may be an issue of high throughput that is causing issue.

**Comment by i-e-b** [comment]
Files should be cleaned up as and when:
- The contained data is consumed
- The session is flushed

DiskQueue does buffer up file deletes, and tries to delete them during a 'finalise' phase. This is done to work around various issues in filesystem implementations.

For reference:
- https://github.com/i-e-b/DiskQueue/blob/master/src/DiskQueue/Implementation/StandardFileDriver.cs
- https://github.com/i-e-b/DiskQueue/blob/master/src/DiskQueue/Implementation/PersistentQueueImpl.cs#L746
- https://github.com/i-e-b/DiskQueue/blob/master/src/DiskQueue/Implementation/PersistentQueueImpl.cs#L170

**Comment by wwaldner-amtelco** [comment]
Does each dequeue require a flush, or can you dequeue multiple items and then do a single flush.

**Comment by i-e-b** [comment]
You can dequeue multiple items and then flush. This is faster, but the items will appear back on the queue if you fail to flush (due to crash/power failure/etc)
