### ISSUE TITLE
Using .NET Standard.

### ISSUE THREAD

**Issue by pauldotknopf** [i-e-b/DiskQueue#4]
Your library does indeed work with .NET Standard, but there are build warnings.

```
warning NU1701: Package 'DiskQueue 1.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project
```
If I submit a pull request, will you accept and push to NuGet?

**Comment by i-e-b** [comment]
Sure, as long as it works :-)
Thanks.

**Comment by zmhh** [comment]
A NetStandard version appears to be available:

https://www.nuget.org/packages/DiskQueue.NetStandard/
https://github.com/shamork/DiskQueue
