### ISSUE TITLE
[Question] Why does queue try to give Everyone access to queue files and directories? 

### ISSUE THREAD

**Issue by zmhh** [i-e-b/DiskQueue#7]
I'm wondering why the queue tries to give everyone access to the queue files and directories?  

Specifically the two calls to: SetPermissions.TryAllowReadWriteForAll()

**Comment by i-e-b** [comment]
Probably because it suited my needs at the time :-)
I haven't had to use this in a low privilege environment, so there's guarantee it will work.

**Comment by zmhh** [comment]
Thanks Iain
