### ISSUE TITLE
Persistence on app close?

### ISSUE THREAD

**Issue by PaulFake** [i-e-b/DiskQueue#8]
If data is persisted on disk when the app is closed, the queue doesn't appear to read that data and fill itself when the app is restarted.  Is that not a supported use case for this library?

**Comment by i-e-b** [comment]
That is the primary purpose of the library, and is covered by multiple test cases. Could you provide an example of what you mean?

**Comment by PaulFake** [comment]
Good to know - I'm probably just using it wrong then.  I'm opening/creating the queue on startup:

`_queue = PersistentQueue.WaitFor(path + "RetainedMessages", new TimeSpan(0, 0, 10));`

Writing to it a few thousand times:

```
using (var session = _queue.OpenSession())
{
    session.Enqueue(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(messages[messages.Count - 1])));
    session.Flush();
}
```

Then closing the app, at which point the data0 file on disk has grown to a few MB.  Then I restart the app, which again calls:

`_queue = PersistentQueue.WaitFor(path + "RetainedMessages", new TimeSpan(0, 0, 10));`

And then attempts to load data from the queue:

```
using (var session = _queue.OpenSession())
{
    byte[] data;
    while ((data = session.Dequeue()) != null)
    {
        etc...
    }
    session.Flush();
}
```

It never gets inside the while() block, because session.Dequeue() is null.  When I examine the _queue object after WaitFor(), it shows an estimated size of zero.

**Comment by i-e-b** [comment]
How are you checking that the while loop is never entered?
It might be worth trying to pull a single item from the queue and step through it with the debugger.

Also, what .Net version and OS is this?

**Comment by PaulFake** [comment]
I was checking the while loop with the debugger.  I'm using .NET Standard 2.0 on Win 7 64 bit.  The library I'm using is actually a fork of yours by some other dude *ducks quickly to avoid being punched*.  Perhaps the problem is in his code and not yours, so I'll work on figuring it out for myself now that I know there wasn't anything obviously wrong in the code I wrote.  Thanks for your help.
