### ISSUE TITLE
Any thoughts to persist the file name as well?

### ISSUE THREAD

**Issue by veerupotru** [i-e-b/DiskQueue#9]
First my apologies to create this as "ISSUE" since I couldn't find your contact details. 
Is it possible to persist the file name as well along with file bytes? I couldn't see a way to do that. Do you have any alternate solutions to capture the file name with bytes? 

Thanks in advance!

**Comment by veerupotru** [comment]
I know one way to do that is by serializing a class with bytes and file name but I wonder if there is a way which is in-built in this API

**Comment by i-e-b** [comment]
You supply the file path as part of the connection process. See `PersistentQueue.WaitFor(path, timeout)`
